### ISSUE TITLE
Bug: Deleting camera won't delete inserted roll

### ISSUE THREAD

**Issue by TheoThmn** [ZieglerAaron/filmfriend-frontend#5]
When deleting a camera on the camera-view the assigned roll is not deleted, resulting in a stub-roll in db.

**Comment by ZieglerAaron** [comment]
Fixed with [c3b7f02](https://github.com/ZieglerAaron/filmfriend-frontend/commit/c3b7f0266c15669a4ad459036f2234b90aebced2)
